version: '3.8'
services:

  database:
    image: postgres
    networks:
      - ft_transcendence
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    ports:
      - 5434:5434
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user-name@domain-name.com
      - PGADMIN_DEFAULT_PASSWORD=strong-password
    ports:
      - "8888:80"
    restart: always

  backend:
    volumes:
      - ./backend:/app
    networks:
      - ft_transcendence
    build:
      context: ./
      dockerfile: Dockerfile.back
    ports:
      - 3030:3030
    depends_on:
      - database

  frontend:
    volumes:
      - ./frontend:/app
    networks:
      - ft_transcendence
    build:
      context: ./
      dockerfile: Dockerfile.front
    ports:
      - 8080:3000
    depends_on:
      - database

networks:
  ft_transcendence:
