version: '3.8'
services:

  database:
    image: postgres:latest
    container_name: database_container
    env_file:
      - database.env
    restart: always
    networks:
      - ft_transcendence

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      - database
    networks:
      - ft_transcendence

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
      - api.env
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
