version: '3.8'
services:

  database:
    image: postgres:latest
    container_name: database_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ft_transcendence

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - ft_transcendence

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.back
    ports:
      - 3030:3030
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - ft_transcendence

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.front
    ports:
      - 8080:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - database
    networks:
      - ft_transcendence

volumes:
  postgres_data:
  pgadmin-data:

networks:
  ft_transcendence:
