version: '3.8'
services:

  database:
    image: postgres:latest
    container_name: database_container
    env_file:
      - database.env
    restart: always
    networks:
      - ft_transcendence

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
      - api.env
    depends_on:
      - database
    networks:
      - ft_transcendence
    ports:
      - "3000:3000"

networks:
  ft_transcendence:
