FROM node:lts

RUN apt-get update -y && apt-get upgrade -y

WORKDIR /app

RUN npm install -g @nestjs/cli

EXPOSE 3030

CMD [ "/bin/bash", "-c", "npm install && npm install --save @nestjs/typeorm typeorm pg && npm run start:dev" ]
